[package]
name = "tiny-secp256k1"
version = "0.2.0"
authors = [
    "Kirill Fomichev <fanatid@ya.ru>",
    "Jonathan Underwood <junderwood@bitcoinbank.co.jp>"
]
edition = "2018"
description = "A Rust library for building tiny-secp256k1 WASM."
rust-version = "1.50"
license = "MIT"

[lib]
crate-type = ["lib"]

[features]
default = ["rand"]
no_std = []
minimal_validation = []

[dependencies]
secp256k1 = { version = "0.20.3", default-features = false }
rand = { version = "0.8.4", optional = true }
