[package]
name = "tiny-secp256k1"
version = "0.2.0"
authors = [
    "Kirill Fomichev <fanatid@ya.ru>",
    "Jonathan Underwood <junderwood@bitcoinbank.co.jp>"
]
edition = "2018"
description = "A Rust library for building tiny-secp256k1 WASM."
rust-version = "1.50"
license = "MIT"

[lib]
crate-type = ["lib"]

[features]
default = ["rand"]
no_std = []
minimal_validation = []

[dependencies]
# This commit is on top of 0.22.1 (removing duplicate symbols so WASM can compile at all)
secp256k1 = { git = "https://github.com/junderw/rust-secp256k1", rev = "e88fc67a61b79565626b25fc08d6816e23f84cf6", default-features = false, features = ["recovery"] }
rand = { version = "0.8.4", optional = true }
