name: ReactExample

on:
  push:
    branches:
    - master

env:
  NODE_VERSION: 14.0.0

jobs:
  publish-react-app:
    name: Publish react example
    runs-on: ubuntu-latest
    steps:
    - name: Fetch code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install Rust stable with wasm32-unknown-unknown
      run: rustup toolchain install stable --target wasm32-unknown-unknown

    - name: Install Node.js dependencies
      run: |
        npm ci
        cd examples/react-app && npm ci

    - uses: actions/cache@v2
      id: binaryen-cache
      with:
        path: binaryen-version_112
        key: binaryen-version_112

    - name: Install wasm-opt (binaryen)
      if: steps.binaryen-cache.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/WebAssembly/binaryen/releases/download/version_112/binaryen-version_112-x86_64-linux.tar.gz
        tar zxvf binaryen-version_112-x86_64-linux.tar.gz

    - name: Build wasm
      run: export PATH=$PATH:./binaryen-version_112/bin/ && make build-wasm

    - name: Build JS
      run: make build-js

    - name: Build react-app
      run: cd examples/react-app && npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: examples/react-app/dist
